task:
  name: Linux
  container:
    image: rust:latest
  build_script: cargo build --all-features --all-targets --all
  test_script: cargo test --all-features --all-targets --all

task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: ${PATH};${USERPROFILE}\.cargo\bin
  install_script:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe -y --default-toolchain stable
  build_script: cargo build --all-features --all-targets --all
  test_script: cargo test --all-features --all-targets --all

task:
  name: macOS
  osx_instance:
    image: mojave-base
  install_script: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  build_script: cargo build --all-features --all-targets --all
  test_script: cargo test --all-features --all-targets --all

# test_task:
#   matrix:
#     - container:
#         image: rust:latest
#     -
#     - osx_instance:
#         image: mojave-base
#     - freebsd_instance:
#         image: freebsd-12-0-release-amd64
#   build_script: cargo build --all-features --all-targets --all
#   test_script: cargo test --all-features --all-targets --all
