test_task:
  matrix:
    - container:
        image: rust:latest
    - allow_failures: true
      container:
        image: rustlang/rust:nightly
  build_script: cargo build --all-features --all-targets --all
  test_script: cargo test --all-features --all-targets --all
