# Lint with rustfmt and Clippy
lint_template: &LINT_TEMPLATE
  rustfmt_script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  clippy_script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features --all -- -D warnings -W clippy::pedantic

# Build and test against the version of Rust specified in `rust-toolchain`
test_template: &TEST_NIGHTLY_TEMPLATE
  test_script: cargo test --all-features --all-targets --all

# Audit `Cargo.lock` for dependencies with security vulnerabilities
audit_template: &AUDIT_TEMPLATE
  audit_script:
    - cargo install cargo-audit
    - cargo generate-lockfile
    - cargo audit

# Linux
task:
  name: Linux
  container:
    image: rust:latest
  <<: *LINT_TEMPLATE
  <<: *TEST_TEMPLATE
  <<: *AUDIT_TEMPLATE

# Windows
task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  env:
    PATH: $USERPROFILE\.cargo\bin;$PATH
  install_script:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe -y --default-toolchain none
  <<: *TEST_TEMPLATE

# macOS and FreeBSD
task:
  matrix:
    - name: macOS
      osx_instance:
        image: mojave-base
    - name: FreeBSD
      freebsd_instance:
        image: freebsd-12-0-release-amd64
  env:
    PATH: $HOME/.cargo/bin:$PATH
  install_script: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
  <<: *TEST_TEMPLATE
