# check_template: &CHECK_TEMPLATE
#   add_components_script: rustup component add clippy rustfmt
#   rustfmt_script: cargo fmt --all -- --check
#   clippy_script: cargo clippy --all-targets --all-features --all -- -D warnings -W clippy::pedantic
#   test_script: cargo test --all-features --all-targets --all

# task:
#   name: Linux
#   container:
#     image: rust:latest
#   << : *CHECK_TEMPLATE

task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $PATH;$USERPROFILE\.cargo\bin
  install_script:
    - choco install visualstudio2017buildtools -y
    # - curl -sSf -o rustup-init.exe https://win.rustup.rs
    # - rustup-init.exe -y --default-toolchain stable
  echo_script:
    - cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
    - dir link.exe /s /p
  # << : *CHECK_TEMPLATE

# task:
#   matrix:
#     - name: macOS
#       osx_instance:
#         image: mojave-base
#     - name: FreeBSD
#       freebsd_instance:
#         image: freebsd-12-0-release-amd64
#   env:
#     PATH: $PATH:$HOME/.cargo/bin
#   install_script: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
#   build_script: cargo build --all-features --all-targets --all
#   test_script: cargo test --all-features --all-targets --all
