test_template: &TEST_TEMPLATE
  test_script: cargo test --all-targets --all-features --all

# Linux
task:
  name: Test on Linux
  container:
    image: rust:latest
  install_script:
    - rustup default beta
  rustfmt_script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  clippy_script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features --all -- -D warnings
  <<: *TEST_TEMPLATE

# Windows
task:
  name: Test on Windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  env:
    PATH: $USERPROFILE\.cargo\bin;$PATH
  install_script:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe -y --default-toolchain beta
  <<: *TEST_TEMPLATE

# macOS and FreeBSD
task:
  matrix:
    - name: Test on macOS
      osx_instance:
        image: mojave-base
    - name: Test on FreeBSD
      freebsd_instance:
        image: freebsd-12-0-release-amd64
  env:
    PATH: $HOME/.cargo/bin:$PATH
  install_script: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain beta
  <<: *TEST_TEMPLATE

# Audit `Cargo.lock` for dependencies with security vulnerabilities
task:
  name: Audit dependencies
  container:
    image: rust:latest
  audit_script:
    - cargo install cargo-audit
    - cargo generate-lockfile
    - cargo audit
